variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}

stages:
- build
- deploy

build:
  stage: build
  image:
    name: docker
  variables:
    BRANDING: villasweb
    DOCKER_TAG: ${CI_COMMIT_BRANCH}-${BRANDING}
  script:
  - docker build --build-arg REACT_APP_BRAND=${BRANDING} --tag ${DOCKER_IMAGE}:${DOCKER_TAG} .
  tags:
  - docker

build.slew:
  variables:
    BRANDING: slew
    DOCKER_TAG: ${CI_COMMIT_BRANCH}-${BRANDING}
  extends: build

deploy.latest:
  stage: deploy
  variables:
    DOCKER_TAG: latest
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  only:
    refs:
    - master
  tags:
  - docker
  dependencies:
  - build

deploy.slew:
  stage: deploy
  variables:
    BRANDING: slew
    DOCKER_TAG: ${CI_COMMIT_BRANCH}-${BRANDING}
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
  - docker
  dependencies:
  - build.slew
