variables:
  GIT_SUBMODULE_STRATEGY: normal

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

stages:
  - prepare
  - build
  - test
  
prepare:
  stage: prepare
  script:
    - docker build -t villas/web-dev .
  tags:
    - linux
    - shell

build_job:
  stage: build
  before_script:
    - mkdir -p build
  script:
    - npm install
    - npm run build
  image: villas/web-dev
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  tags:
    - docker

test_job:
  stage: test
  script:
    - npm test
  image: villas/web-dev
  dependencies:
    - build_job
  tags:
    - docker
