variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_TAG: ${CI_COMMIT_BRANCH}
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

#cache:
#  untracked: true
#  key: ${CI_PROJECT_ID}
#  paths:
#    - node_modules/
#    - _site/vendor/
#    - .bundled/
#    - .yarn

stages:
  - build
  - deploy

build:
  stage: build
  image: node:16.5
  before_script:
    - mkdir -p build
  script:
    - npm install
    - npm run build
#  artifacts:
#    paths:
#      - build/
#    expire_in: 1 week

deploy:default:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --build-arg REACT_APP_BRAND=villasweb
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${DOCKER_IMAGE}:${DOCKER_TAG}
      --snapshotMode=redo
  dependencies:
    - build

deploy:slew:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --build-arg REACT_APP_BRAND=slew
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${DOCKER_IMAGE}:${DOCKER_TAG}-slew
      --snapshotMode=redo
  dependencies:
    - build
