variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_TAG: ${CI_COMMIT_BRANCH}
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}

cache:
  untracked: true
  key: ${CI_PROJECT_ID}
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

stages:
  - build
  - deploy

build:
  stage: build
  image: node:12.2
  before_script:
    - mkdir -p build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${DOCKER_IMAGE}:${DOCKER_TAG}
      --snapshotMode=redo
  dependencies:
    - build
