image: docker

variables:
  GIT_SUBMODULE_STRATEGY: normal

services:
- docker:dind

before_script:
- docker version
- apk add --no-cache py-pip
- pip install docker-compose
- mkdir -p build

cache:
  paths:
  - build

stages:
- build
- test
- deploy

build_job:
  stage: build
  script:
  - docker run --rm -v $(pwd)/package.json:/usr/src/app/package.json -v $(pwd)/build:/usr/src/app/build -v $(pwd)/public:/usr/src/app/public -v $(pwd)/src:/usr/src/app/src -w /usr/src/app node:7.9.0-slim bash -c 'npm install; npm run build'
  tags:
  - docker

test_job:
  stage: test
  script:
  - docker run --rm -e CI=true -v $(pwd)/package.json:/usr/src/app/package.json -v $(pwd)/public:/usr/src/app/public -v $(pwd)/src:/usr/src/app/src -w /usr/src/app node:7.9.0-slim bash -c 'npm install; npm test'
  tags:
  - docker

deploy_review:
  stage: deploy
  environment: review
  script:
  - mkdir -p ~/.docker
  - echo $DEPLOYMENT_CACERT > ~/.docker/ca.pem
  - echo $DEPLOYMENT_CLIENT_CERT > ~/.docker/cert.pem
  - echo $DEPLOYMENT_CLIENT_KEY > ~/.docker/key.pem
  - docker-compose build
  - docker-compose -d --tlsverify -H=$DEPLOYMENT_HOST down
  - docker-compose -d --tlsverify -H=$DEPLOYMENT_HOST up
  tags:
  - docker
