variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE_DEV: node:12.2
  DOCKER_IMAGE: ${CI_REGISTRY}/acs/public/villas/web

cache:
  untracked: true
  key: ${CI_PROJECT_ID}
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - mkdir -p build
  script:
    - npm install
    - npm run build
  image: ${DOCKER_IMAGE_DEV}
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  tags:
    - docker

#test:
#  stage: test
#  script:
#    - npm test
#  image: ${DOCKER_IMAGE_DEV}
#  dependencies:
#    - build
#  tags:
#    - docker

deploy:docker:
  stage: deploy
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  tags:
    - shell
    - linux
  only:
   refs:
     - master
     - develop
