variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}

stages:
  - build
  - deploy

build.npm:
  stage: build
  image: node:16.5
  variables:
    CI: "false"
  before_script:
  - mkdir -p build
  script:
  - npm install --force
  - npm run build

deploy.default:
  stage: deploy
  image:
    name: docker
  variables:
    BRANDING: villasweb
    DOCKER_TAG: ${CI_COMMIT_BRANCH}-${BRANDING}
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker build --build-arg REACT_APP_BRAND=${BRANDING} --tag ${DOCKER_IMAGE}:${DOCKER_TAG} .
  dependencies:
  - build.npm
  tags:
  - docker

deploy.slew:
  variables:
    BRANDING: slew
    DOCKER_TAG: ${CI_COMMIT_BRANCH}-${BRANDING}
  extends: deploy.default

# Deploy latest tag on master branch
deploy.latest:
  variables:
    BRANDING: villasweb
    DOCKER_TAG: latest
  extends: deploy.default
  only:
    refs:
    - master
