version: "2"

services:
  webserver:
    image: nginx:stable
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - website-volume:/www
    links:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: always

  frontend:
    build: .
    volumes:
      - ./:/react
      - website-volume:/result

  backend:
    image: villasweb-backend
    links:
      - database
    environment:
      - NODE_ENV=production
    restart: always

  database:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    restart: always

volumes:
  data-volume:
  website-volume:
