version: "2"

volumes:
  database:
    driver: local

services:
  frontend:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - backend
    environment:
      - REACT_APP_HTTP_PROXY
    ports:
      - "80:80"
      - "443:443"
    restart: always

  backend:
    build: backend
    links:
      - database
      - broker
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: always

  database:
    image: mongo:latest
    user: mongodb
    volumes:
      - database:/data/db
    restart: always
    user: mongodb

  broker:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=villas
      - RABBITMQ_DEFAULT_PASS=s3c0sim4!
    ports:
      - "8080:15672"
      - "5672:5672"