version: "2"

services:
  frontend:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - backend
    ports:
      - "80:80"
      - "443:443"

  backend:
    build: VILLASweb-backend
    links:
      - database
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"

  database:
    image: mongo:latest
    user: mongodb
    volumes:
      - /opt/database:/data/db
