version: "2"

volumes:
  database:
    driver: local

networks:
  villas:

services:
  # The VILLASweb frontend
  frontend:
    build: 
      context: .
    environment:
      - REACT_APP_HTTP_PROXY
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      villas:

  # The VILLASweb backend
  backend:
    build: backend
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: always
    networks:
      villas:

  # The MongoDB database for the VILLASweb backend
  database:
    image: mongo:latest
    user: mongodb
    volumes:
      - database:/data/db
    expose:
      - "27017"
    restart: always
    user: mongodb
    networks:
      villas:

  # AMQP broker for VILLAScontroller
  broker:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: "villas"
      RABBITMQ_DEFAULT_PASS: "s3c0sim4!"
    ports:
      - "8080:15672"
      - "5672:5672"
    networks:
      villas:

  # VILLASnode, the gateway between UDP and WebSocket traffic
  node:
    image: villas/node:latest
    privileged: true
    command: node /etc/villas/node/websocket-demo.conf
    volumes:
      - "./etc/node/:/etc/villas/node/"
    networks:
      villas: